Repository pangseon/LightHouseAI, pull requests merged in 2024-04, with the labels that each got.

#4 Domain/refactor
  src/main/java/com/mju/lighthouseai/domain/board/entity/Board.java
  src/main/java/com/mju/lighthouseai/domain/board_review/entity/BoardReview.java
  src/main/java/com/mju/lighthouseai/domain/cafe/entity/Cafe.java
  src/main/java/com/mju/lighthouseai/domain/constiuency/entity/Constiuency.java
  src/main/java/com/mju/lighthouseai/domain/other_service/entity/OtherService.java
  src/main/java/com/mju/lighthouseai/domain/region/entity/Region.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/entity/Restaurant.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/entity/ShoppingMall.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/entity/TourList.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor/entity/Travel_Visitor.java
  src/main/java/com/mju/lighthouseai/domain/user/entity/User.java
  src/main/java/com/mju/lighthouseai/domain/user/entity/UserRole.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/AlreadyExistsTestException.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/ForbiddenAccessTestException.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/NotFoundTestException.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/TestErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/user/repository/UserRepository.java
  src/main/java/com/mju/lighthouseai/global/security/UserDetailsImpl.java
  src/main/java/com/mju/lighthouseai/global/security/UserDetailsServiceImpl.java
  src/main/java/com/mju/lighthouseai/sample/controller/TestController.java
  src/main/java/com/mju/lighthouseai/sample/service/TestService.java
  src/main/java/com/mju/lighthouseai/sample/service/impl/TestServiceImpl.java
Labels: feature

#6 Admin/cafe - 카페 추가 기능 생성 및 WebSecurity filter 기능 Off 설정
  build.gradle
  src/main/java/com/mju/lighthouseai/LightHouseAiApplication.java
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/controller/CafeCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/service/request/CafeCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/entity/Cafe.java
  src/main/java/com/mju/lighthouseai/domain/cafe/mapper/dto/CafeDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/cafe/mapper/service/CafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/cafe/repository/CafeRepository.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/CafeService.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/config/JpaConfig.java
  src/main/java/com/mju/lighthouseai/global/config/RestTemplateConfig.java
Labels: feature, refactor

#14 Refactor/user/jwt - cookie 주석처리 및 refreshtoken 삭제
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/jwt/JwtUtil.java
Labels: refactor

#16 Feature/user/update - User Update 기능 추가 및 필요 없는 responseDto 변수 삭제
  src/main/java/com/mju/lighthouseai/domain/user/controller/UserController.java
  src/main/java/com/mju/lighthouseai/domain/user/dto/controller/UpdateUserControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/user/dto/service/request/UpdateUserServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/MatchCurrentPasswordException.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/UserErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/user/mapper/dto/UserDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/user/service/UserService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
Labels: feature, refactor

#19 Feature/admin/cafe/update
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/controller/CafeUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/service/request/CafeUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/entity/Cafe.java
  src/main/java/com/mju/lighthouseai/domain/cafe/exceoption/AlreadyExistsCafeException.java
  src/main/java/com/mju/lighthouseai/domain/cafe/exceoption/CafeErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/cafe/exceoption/ForbiddenAccessCafeException.java
  src/main/java/com/mju/lighthouseai/domain/cafe/exceoption/NotFoundCafeException.java
  src/main/java/com/mju/lighthouseai/domain/cafe/mapper/dto/CafeDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/CafeService.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
Labels: feature, refactor

#21 Feature: Kakao 소셜 로그인 기능 추가
  src/main/java/com/mju/lighthouseai/domain/user/controller/KakaoController.java
  src/main/java/com/mju/lighthouseai/domain/user/dto/kakao/KakaoUserInfoDto.java
  src/main/java/com/mju/lighthouseai/domain/user/service/KakaoService.java
Labels: feature

#25 Feature/refreshtoken - RefreshToken 부분 추가
  build.gradle
  src/main/java/com/mju/lighthouseai/domain/user/controller/UserController.java
  src/main/java/com/mju/lighthouseai/domain/user/service/KakaoService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/NaverService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/UserService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/config/RedisConfig.java
  src/main/java/com/mju/lighthouseai/global/jwt/JwtUtil.java
  src/main/java/com/mju/lighthouseai/global/jwt/RefreshToken.java
  src/main/java/com/mju/lighthouseai/global/jwt/RefreshTokenRepository.java
Labels: feature

#29 Refactor/admin/cafe/create - 카페 생성 시 유저 데이터 추가
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/cafe/entity/Cafe.java
  src/main/java/com/mju/lighthouseai/domain/cafe/mapper/service/CafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/CafeService.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
Labels: feature, refactor

#32 Feature/region - Region Create, Update, Delete 기능 추가 및 SecurityFilterChain에 cafe, region 수정 및 삭제 ADMIN 권한 주석 처리
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/region/controller/RegionController.java
  src/main/java/com/mju/lighthouseai/domain/region/dto/controller/RegionCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/region/dto/controller/RegionUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/region/dto/service/request/RegionCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/region/dto/service/request/RegionUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/region/entity/Region.java
  src/main/java/com/mju/lighthouseai/domain/region/exception/AlreadyExistsRegionException.java
  src/main/java/com/mju/lighthouseai/domain/region/exception/NotFoundRegionException.java
  src/main/java/com/mju/lighthouseai/domain/region/exception/RegionErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/region/mapper/dto/RegionDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/region/mapper/service/RegionEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/region/repository/RegionRepository.java
  src/main/java/com/mju/lighthouseai/domain/region/service/RegionService.java
  src/main/java/com/mju/lighthouseai/domain/region/service/impl/RegionServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/config/WebSecurityConfig.java
Labels: feature

#35 Feature/constituency - Constituency Create, Update, Delete 기능 추가 및 createAuthentication 수정 및 filterChain 권한 부여 추가
  src/main/java/com/mju/lighthouseai/domain/constituency/controller/ConstituencyController.java
  src/main/java/com/mju/lighthouseai/domain/constituency/dto/controller/ConstituencyCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/constituency/dto/controller/ConstituencyUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/constituency/dto/service/request/ConstituencyCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/constituency/dto/service/request/ConstituencyUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/constituency/entity/Constituency.java
  src/main/java/com/mju/lighthouseai/domain/constituency/exception/ConstituencyErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/constituency/exception/NotFoundConstituencyException.java
  src/main/java/com/mju/lighthouseai/domain/constituency/mapper/dto/ConstituencyDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/constituency/mapper/service/ConstituencyEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/constituency/repository/ConstituencyRepository.java
  src/main/java/com/mju/lighthouseai/domain/constituency/service/ConstituencyService.java
  src/main/java/com/mju/lighthouseai/domain/constituency/service/impl/ConstituencyServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/config/WebSecurityConfig.java
  src/main/java/com/mju/lighthouseai/global/jwt/JwtAuthenticationFilter.java
Labels: feature, refactor

#37 Feature/cafe/read all
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/service/response/CafeReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/mapper/service/CafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/CafeService.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
Labels: feature

#49 Feature/shoppingmall/create
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/controller/ShoppingMallController.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/dto/controller/ShoppingMallCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/dto/service/ShoppingMallCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/entity/ShoppingMall.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/exception/AlreadyExistsShoppingMallListException.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/exception/ForbiddenAccessShoppingMallException.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/exception/NotFoundShoppingMallException.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/exception/ShoppingMallErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/mapper/dto/ShoppingMallDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/mapper/service/ShoppingMallEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/repository/ShoppingMallRepository.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/service/ShoppingMallService.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/service/impl/ShoppingMallServiceImpl.java
Labels: feature

#51 Feature/user/get logout - User get, logout 기능 추가 및 token 검증 기능 수정 및 추가
  src/main/java/com/mju/lighthouseai/domain/user/controller/UserController.java
  src/main/java/com/mju/lighthouseai/domain/user/exception/ForbiddenAccessException.java
  src/main/java/com/mju/lighthouseai/domain/user/service/UserService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/jwt/JwtUtil.java
  src/main/java/com/mju/lighthouseai/global/jwt/exception/ExpiredJwtAccessTokenException.java
  src/main/java/com/mju/lighthouseai/global/jwt/exception/ExpiredJwtRefreshTokenException.java
  src/main/java/com/mju/lighthouseai/global/jwt/exception/FailedJwtTokenException.java
  src/main/java/com/mju/lighthouseai/global/jwt/exception/JwtErrorCode.java
Labels: feature, refactor

#53 Feature/tour list/update
  src/main/java/com/mju/lighthouseai/domain/tour_list/controller/TourListController.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/dto/controller/TourListUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/dto/service/TourListUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/entity/TourList.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/exceoption/TourListErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/mapper/dto/TourListDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/TourListService.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/impl/TourListServiceImpl.java
Labels: feature

#55 Feature/tour list/delete
  src/main/java/com/mju/lighthouseai/domain/tour_list/controller/TourListController.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/TourListService.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/impl/TourListServiceImpl.java
Labels: feature

#57 Feature/restaurant - Restaurant update, readall, delete 기능 추가 및 OtherService, Shoppingmall에 필요 없는 패키지 삭제
  src/main/java/com/mju/lighthouseai/domain/other_service/controller/OtherServiceController.java
  src/main/java/com/mju/lighthouseai/domain/other_service/service/OtherService.java
  src/main/java/com/mju/lighthouseai/domain/other_service/service/impl/OtherServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/controller/RestaurantReadAllControllerResquestDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/controller/RestaurantUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/service/request/RestaurantCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/service/request/RestaurantUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/service/response/RestaurantReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/entity/Restaurant.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/mapper/dto/RestaurantDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/mapper/service/RestaurantEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/service/RestaurantService.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/service/impl/RestaurantServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/controller/ShoppingMallController.java
Labels: feature, refactor

#59 Feature/tour list/read all
  src/main/java/com/mju/lighthouseai/domain/tour_list/controller/TourListController.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/dto/service/request/TourListCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/dto/service/request/TourListUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/dto/service/response/TourListReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/mapper/dto/TourListDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/mapper/service/TourListEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/TourListService.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/impl/TourListServiceImpl.java
Labels: feature, refactor

#62 Feature/shoppingmall/update
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/controller/ShoppingMallController.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/dto/controller/ShoppingMallUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/dto/service/ShoppingMallUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/entity/ShoppingMall.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/mapper/dto/ShoppingMallDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/service/ShoppingMallService.java
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/service/impl/ShoppingMallServiceImpl.java
Labels: feature

#65 Refactor/restaurant/update - 음식점 업데이트, 삭제, 전체 조회, 단건 조회 기능 수정 및 추가
  src/main/java/com/mju/lighthouseai/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/controller/RestaurantReadAllControllerResquestDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/dto/service/response/RestaurantReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/entity/Restaurant.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/mapper/service/RestaurantEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/service/RestaurantService.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/service/impl/RestaurantServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/dto/service/response/TourListReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/mapper/service/TourListEntityMapper.java
Labels: feature, refactor, style
