Repository pangseon/LightHouseAI, pull requests merged in 2024-05, with the labels that each got.

#74 feature: s3 연결을 위한 초기 작업
  build.gradle
  src/main/java/com/mju/lighthouseai/global/config/S3Config.java
Labels: feature

#76 feature: aws s3를 이용한 CUD 기능 구현
  src/main/java/com/mju/lighthouseai/global/s3/S3Provider.java
Labels: feature

#72 Board/frist,second repair
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/controller/BoardCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/controller/BoardUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/request/BoardCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/request/BoardUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/respone/BoardReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/board/entity/Board.java
  src/main/java/com/mju/lighthouseai/domain/board/exceoption/BoardErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/board/exceoption/ForbiddenAccessBoardException.java
  src/main/java/com/mju/lighthouseai/domain/board/exceoption/NotFoundBoardException.java
  src/main/java/com/mju/lighthouseai/domain/board/mapper/dto/BoardDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/board/mapper/service/BoardEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/board/repository/BoardRepository.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
Labels: feature

#78 Refactor/jwt/refresh - refreshAccessToken 기능 수정 및 kakao, naver 생일 저장 수정
  src/main/java/com/mju/lighthouseai/domain/user/controller/KakaoController.java
  src/main/java/com/mju/lighthouseai/domain/user/controller/UserController.java
  src/main/java/com/mju/lighthouseai/domain/user/dto/kakao/KakaoUserInfoDto.java
  src/main/java/com/mju/lighthouseai/domain/user/service/KakaoService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/NaverService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/UserService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/config/WebSecurityConfig.java
  src/main/java/com/mju/lighthouseai/global/jwt/JwtUtil.java
  src/main/java/com/mju/lighthouseai/global/jwt/RefreshToken.java
  src/main/java/com/mju/lighthouseai/global/jwt/RefreshTokenRepository.java
Labels: refactor, style

#80 Refactor/board
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/controller/BoardCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/controller/BoardUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/request/BoardCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/request/BoardUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/respone/BoardReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/board/entity/Board.java
  src/main/java/com/mju/lighthouseai/domain/board/exception/BoardErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/board/exception/ForbiddenAccessBoardException.java
  src/main/java/com/mju/lighthouseai/domain/board/exception/NotFoundBoardException.java
  src/main/java/com/mju/lighthouseai/domain/board/mapper/service/BoardEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/s3/S3Provider.java
Labels: feature, refactor

#82 Feature/user/s3 - User upate 시 multipartFile 추가
  src/main/java/com/mju/lighthouseai/domain/user/controller/UserController.java
  src/main/java/com/mju/lighthouseai/domain/user/dto/controller/UserSignUpControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/user/dto/service/request/UserSignUpServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/user/mapper/entity/UserEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/user/service/UserService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
Labels: feature, refactor

#84 Feature/entity/travel - 여행지 컨텐츠 (기본. 텍스트, 이미지, 방문지) 및 여행지 방문지(카페, 음식점, 쇼핑몰, 관광지, 기타서비스) entitiy 추가
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/travel_content/entity/TravelContent.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_image/entity/TravelContentImage.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_text/entity/TravelContentText.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_visitor/entity/TravelContentVisitor.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor/entity/Travel_Visitor.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/entity/TravelVisitorCafe.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/entity/TravelVisitorOtherService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/entity/TravelVisitorRestaurant.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/entity/TravelVisitorShoppingMall.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/entity/TravelVisitorTourList.java
Labels: feature

#86 Feature/travel visitor cafe/crud - 여행지 방문지 카페 crud
  src/main/java/com/mju/lighthouseai/domain/cafe/repository/CafeRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/controller/TravelVisitorCafeController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/controller/TravelVisitorCafeCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/controller/TravelVisitorCafeUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/request/TravelVisitorCafeCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/request/TravelVisitorCafeUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/response/TravelVisitorCafeReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/entity/TravelVisitorCafe.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/exception/NotFoundTravelVisitorCafeException.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/exception/TravelVisitorCafeErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/dto/TravelVisitorCafeDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/service/TravelVisitorCafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/repository/TravelVisitorCafeRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/TravelVisitorCafeService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/impl/TravelVisitorCafeServiceImpl.java
Labels: feature

#88 Feature/travel visitor restaurant/crud - 여행지 방문지 음식점 crud
  src/main/java/com/mju/lighthouseai/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/controller/TravelVisitorRestaurantController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/controller/TravelVisitorRestaurantCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/controller/TravelVisitorRestaurantUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/service/request/TravelVisitorRestaurantCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/service/request/TravelVisitorRestaurantUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/service/response/TravelVisitorRestaurantReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/entity/TravelVisitorRestaurant.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/exception/NotFoundTravelVisitorRestaurant.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/exception/TravelVisitorRestaurantErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/mapper/dto/TravelVisitorRestaurantDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/mapper/service/TravelVisitorRestaurantEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/repository/TravelVisitorRestaurantRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/service/TravelVisitorRestaurantService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/service/impl/TravelVisitorRestaurantServiceImpl.java
Labels: feature

#90 Feature/travel visitor shoppingmall/crud - 여행지 방문지 쇼핑몰 crud
  src/main/java/com/mju/lighthouseai/domain/shoppingmall/repository/ShoppingMallRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/controller/TravelVisitorShoppingMallController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/controller/TravelVisitorShoppingMallCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/controller/TravelVisitorShoppingMallUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/service/request/TravelVisitorShoppingMallCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/service/request/TravelVisitorShoppingMallUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/service/response/TravelVisitorShoppingMallReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/entity/TravelVisitorShoppingMall.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/exception/NotFoundTravelVisitorShoppingMallException.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/exception/TravelVisitorShoppingMallErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/mapper/dto/TravelVisitorShoppingMallDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/mapper/service/TravelVisitorShoppingMallEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/repository/TravelVisitorShoppingMallRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/service/TravelVisitorShoppingMallService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/service/impl/TravelVisitorShoppingMallServiceImpl.java
Labels: feature

#92 Feature/travel visitor tourlist/crud - 여행지 방문지 관광지 crud
  src/main/java/com/mju/lighthouseai/domain/tour_list/repository/TourListRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/controller/TravelVisitorTourListController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/controller/TravelVisitorTourListCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/controller/TravelVisitorTourListUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/service/request/TravelVisitorTourListCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/service/request/TravelVisitorTourListUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/service/response/TravelVisitorTourListReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/entity/TravelVisitorTourList.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/exception/NotFoundTravelVisitorTourListException.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/exception/TravelVisitorTourListErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/mapper/dto/TravelVisitorTourListDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/mapper/service/TravelVisitorTourListEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/repository/TravelVisitorTourListRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/service/TravelVisitorTourListService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/service/impl/TravelVisitorTourListServiceImpl.java
Labels: feature

#94 Feature/travel visitor otherservice/crud - 여행지 방문지 기타서비스 crud
  src/main/java/com/mju/lighthouseai/domain/other_service/repository/OtherServiceRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_visitor/entity/TravelContentVisitor.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/controller/TravelVisitorOtherServiceController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/controller/TravelVisitorOtherServiceCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/controller/TravelVisitorOtherServiceUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/service/request/TravelVisitorOtherServiceCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/service/request/TravelVisitorOtherServiceUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/service/response/TravelVisitorOtherServiceReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/entity/TravelVisitorOtherServiceEntity.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/exception/NotFoundTravelVisitorOtherServiceException.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/exception/TravelVisitorOtherServiceErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/mapper/dto/TravelVisitorOtherServiceDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/mapper/service/TravelVisitorOtherServiceEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/repository/TravelVisitorOtherServiceRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/service/TravelVisitorOtherService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/service/impl/TravelVisitorOtherServiceImpl.java
Labels: feature

#96 Refactor/board/delete
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
Labels: feature, refactor

#98 Refactor/borad/update
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/controller/BoardUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/request/BoardUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/respone/BoardReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/board/entity/Board.java
  src/main/java/com/mju/lighthouseai/domain/board/mapper/service/BoardEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/board/repository/BoardRepository.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
Labels: feature, refactor

#104 refactor: user create, update 시 프로필 이미지 처리 수정
  src/main/java/com/mju/lighthouseai/domain/user/service/impl/UserServiceImpl.java
Labels: refactor

#106 Feature/treavel
  src/main/java/com/mju/lighthouseai/domain/board/mapper/service/BoardEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel/controller/TravelController.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/controller/TravelCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/controller/TravelUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/request/TravelCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/request/TravelUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/response/TravelVisitorCafeReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel/exception/NotFoundTravelException.java
  src/main/java/com/mju/lighthouseai/domain/travel/exception/TravelErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/travel/mapper/dto/TravelDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel/mapper/service/TravelEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel/repository/TravelRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/TravelService.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_content/entity/TravelContent.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_image/entity/TravelContentImage.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_text/entity/TravelContentText.java
  src/main/java/com/mju/lighthouseai/domain/travel_content_visitor/entity/TravelContentVisitor.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/controller/TravelVisitorCafeController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/controller/TravelVisitorCafeCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/request/TravelVisitorCafeCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/entity/TravelVisitorCafe.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/dto/TravelVisitorCafeDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/service/TravelVisitorCafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/TravelVisitorCafeService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/impl/TravelVisitorCafeServiceImpl.java
Labels: feature, refactor

#107 refactor: TravelVisitorCafeEntityMapper의 toTravelVisitorCafe에서 image_url 매핑 추가
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/service/TravelVisitorCafeEntityMapper.java
Labels: refactor

#109 Refactor/travel/restaurant
  src/main/java/com/mju/lighthouseai/domain/travel/controller/TravelController.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/TravelService.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/controller/TravelVisitorRestaurantController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/entity/TravelVisitorRestaurant.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/mapper/dto/TravelVisitorRestaurantDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/mapper/service/TravelVisitorRestaurantEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/service/TravelVisitorRestaurantService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/service/impl/TravelVisitorRestaurantServiceImpl.java
Labels: feature, refactor

#113 refactor: 여행지 생성 시, 여행지_방문지_관광지 함께 생성 가능하도록 수정
  src/main/java/com/mju/lighthouseai/domain/travel/controller/TravelController.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/TravelService.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/controller/TravelVisitorTourListController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/entity/TravelVisitorTourList.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/mapper/dto/TravelVisitorTourListDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/mapper/service/TravelVisitorTourListEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/service/TravelVisitorTourListService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/service/impl/TravelVisitorTourListServiceImpl.java
Labels: feature, refactor

#115 refactor: 여행지 생성 시, 여행지_방문지_기타 서비스도 함께 생성 가능하도록 수정
  src/main/java/com/mju/lighthouseai/domain/travel/controller/TravelController.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/TravelService.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/controller/TravelVisitorOtherServiceController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/entity/TravelVisitorOtherServiceEntity.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/mapper/dto/TravelVisitorOtherServiceDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/mapper/service/TravelVisitorOtherServiceEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/service/TravelVisitorOtherService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/service/impl/TravelVisitorOtherServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/mapper/service/TravelVisitorTourListEntityMapper.java
Labels: refactor

#117 feature: 여행지 삭제 기능 추가
  src/main/java/com/mju/lighthouseai/domain/cafe/entity/Cafe.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/entity/Restaurant.java
  src/main/java/com/mju/lighthouseai/domain/restaurant/service/impl/RestaurantServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/entity/TourList.java
  src/main/java/com/mju/lighthouseai/domain/tour_list/service/impl/TourListServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel/controller/TravelController.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/controller/TravelCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/request/TravelCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/response/TravelReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/response/TravelVisitorCafeReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel/mapper/service/TravelEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel/repository/TravelRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/TravelService.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/service/TravelVisitorCafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/service/request/TravelVisitorOtherServiceCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/service/request/TravelVisitorRestaurantCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/service/request/TravelVisitorShoppingMallCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/service/request/TravelVisitorTourListCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/user/repository/UserRepository.java
Labels: feature, refactor

#120 feature: travelvisitor들 travelId로 전체 조회 기능 추가
  src/main/java/com/mju/lighthouseai/domain/board/dto/service/respone/BoardReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/controller/TravelVisitorCafeController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/repository/TravelVisitorCafeRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/TravelVisitorCafeService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/impl/TravelVisitorCafeServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/controller/TravelVisitorOtherServiceController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/repository/TravelVisitorOtherServiceRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/service/TravelVisitorOtherService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/service/impl/TravelVisitorOtherServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/controller/TravelVisitorRestaurantController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/repository/TravelVisitorRestaurantRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/service/TravelVisitorRestaurantService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/service/impl/TravelVisitorRestaurantServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/controller/TravelVisitorShoppingMallController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/repository/TravelVisitorShoppingMallRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/service/TravelVisitorShoppingMallService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/service/impl/TravelVisitorShoppingMallServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/controller/TravelVisitorTourListController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/repository/TravelVisitorTourListRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/service/TravelVisitorTourListService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/service/impl/TravelVisitorTourListServiceImpl.java
Labels: feature

#122 Refactor/travel/travelvisitorcafe
  src/main/java/com/mju/lighthouseai/domain/travel/dto/controller/TravelUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/request/TravelUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/dto/service/response/TravelReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel/entity/Travel.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/controller/TravelVisitorCafeController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/controller/TravelVisitorCafeCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/controller/TravelVisitorCafeUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/request/TravelVisitorCafeCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/request/TravelVisitorCafeUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/dto/service/response/TravelVisitorCafeReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/entity/TravelVisitorCafe.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/mapper/service/TravelVisitorCafeEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/repository/TravelVisitorCafeRepository.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/TravelVisitorCafeService.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_cafe/service/impl/TravelVisitorCafeServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/controller/TravelVisitorOtherServiceController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_other_service/dto/service/response/TravelVisitorOtherServiceReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/controller/TravelVisitorRestaurantController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_restaurant/dto/service/response/TravelVisitorRestaurantReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/controller/TravelVisitorShoppingMallController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_shoppingmall/dto/service/response/TravelVisitorShoppingMallReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/controller/TravelVisitorTourListController.java
  src/main/java/com/mju/lighthouseai/domain/travel_visitor_tour_list/dto/service/response/TravelVisitorTourListReadAllServiceResponseDto.java
Labels: feature, refactor

#124 feature: 리뷰 CRUD 구현 및 페이징 처리 완료
  src/main/java/com/mju/lighthouseai/domain/review/controller/ReviewController.java
  src/main/java/com/mju/lighthouseai/domain/review/dto/controller/ReviewCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/review/dto/controller/ReviewUpdateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/review/dto/service/request/ReviewCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/review/dto/service/request/ReviewUpdateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/review/dto/service/response/ReviewReadAllServiceResponseDto.java
  src/main/java/com/mju/lighthouseai/domain/review/entity/Review.java
  src/main/java/com/mju/lighthouseai/domain/review/exception/AlreadyExistsReviewException.java
  src/main/java/com/mju/lighthouseai/domain/review/exception/ForbiddenAccessReviewException.java
  src/main/java/com/mju/lighthouseai/domain/review/exception/NotFoundReviewException.java
  src/main/java/com/mju/lighthouseai/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/review/mapper/dto/ReviewDtoMapper.java
  src/main/java/com/mju/lighthouseai/domain/review/mapper/service/ReviewEntityMapper.java
  src/main/java/com/mju/lighthouseai/domain/review/repository/ReviewRepository.java
  src/main/java/com/mju/lighthouseai/domain/review/service/ReviewService.java
  src/main/java/com/mju/lighthouseai/domain/review/service/impl/ReviewServiceImpl.java
Labels: feature

#128 refactor: 게시판에 대한 페이징 처리를 진행하였습니다
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/repository/BoardRepository.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
Labels: feature

#134 Feature/readallnotpage - Travel, Board 페이징 없는 readAll 추가
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/travel/controller/TravelController.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/TravelService.java
  src/main/java/com/mju/lighthouseai/domain/travel/service/impl/TraveServiceImpl.java
Labels: feature

#132 refactor: 카페에 대한 지역별 검색 기능 추가
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/cafe/repository/CafeRepository.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/CafeService.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
Labels: feature

#101 게시글 좋아요 기증구현
  src/main/java/com/mju/lighthouseai/domain/board/exception/BoardErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/board/exception/NotfoundUserException.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/like/controller/LikeController.java
  src/main/java/com/mju/lighthouseai/domain/like/entity/Like.java
  src/main/java/com/mju/lighthouseai/domain/like/exception/AlreadyExistLikeException.java
  src/main/java/com/mju/lighthouseai/domain/like/exception/LikeErrorCode.java
  src/main/java/com/mju/lighthouseai/domain/like/exception/NotFoundLikeException.java
  src/main/java/com/mju/lighthouseai/domain/like/repository/LikeRepository.java
  src/main/java/com/mju/lighthouseai/domain/like/service/LikeService.java
  src/main/java/com/mju/lighthouseai/domain/like/service/impl/LikeServiceImpl.java
  src/main/java/com/mju/lighthouseai/domain/user/entity/User.java
Labels: feature

#140 Feature/like/islike - Like islike 기능 추가
  src/main/java/com/mju/lighthouseai/domain/like/controller/LikeController.java
  src/main/java/com/mju/lighthouseai/domain/like/service/LikeService.java
  src/main/java/com/mju/lighthouseai/domain/like/service/impl/LikeServiceImpl.java
Labels: feature

#144 feature: Board readAllUserBoards 기능 추가
  src/main/java/com/mju/lighthouseai/domain/board/controller/BoardController.java
  src/main/java/com/mju/lighthouseai/domain/board/repository/BoardRepository.java
  src/main/java/com/mju/lighthouseai/domain/board/service/BoardService.java
  src/main/java/com/mju/lighthouseai/domain/board/service/impl/BoardServiceImpl.java
Labels: feature

#142 Naver/search/cafe
  src/main/java/com/mju/lighthouseai/domain/cafe/controller/CafeController.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/controller/CafeCreateControllerRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/dto/service/request/CafeCreateServiceRequestDto.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/CafeService.java
  src/main/java/com/mju/lighthouseai/domain/cafe/service/impl/CafeServiceImpl.java
  src/main/java/com/mju/lighthouseai/global/naversearch/NaverSearchController.java
  src/main/java/com/mju/lighthouseai/global/naversearch/NaverSearchItem.java
  src/main/java/com/mju/lighthouseai/global/naversearch/NaverSearchResponse.java
  src/main/java/com/mju/lighthouseai/global/naversearch/NaverSearchService.java
Labels: feature, refactor

#145 Feature/ai 비용 인원 이용한 추천 기능
  src/main/python/AIController.py
  src/main/python/Chatbot.py
  src/main/python/__pycache__/Chatbot.cpython-311.pyc
Labels: feature

#152 refactor: 소셜로그인 생일 기본 설정으로 수정
  src/main/java/com/mju/lighthouseai/domain/user/service/KakaoService.java
  src/main/java/com/mju/lighthouseai/domain/user/service/NaverService.java
Labels: refactor
